### ISSUE TITLE
ログイン

### ISSUE THREAD

**Issue by MasayaOsuga** [Swift2023-Group-C/flutter_app#70]

**Comment by tigertora7571** [comment]
ログインしないと使えない機能
・レビュー
・過去問？
・マップ詳細？

**Comment by MasayaOsuga** [comment]
過去問とマップ詳細はどっちでもいいね

**Comment by tigertora7571** [comment]
@MasayaOsuga レビュー投稿したときの処理のuserKeyを`FirebaseAuth.instance.currentUser?.uid`に変えたけど問題なさそう？

**Comment by MasayaOsuga** [comment]
@tigertora7571 たぶん大丈夫？とおもう

**Comment by MasayaOsuga** [comment]
でもfire storeにNULLで入ってる？

**Comment by tigertora7571** [comment]
nullやってないよ
今ロボ技に投稿した

**Comment by MasayaOsuga** [comment]
できてるね
